apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: zlqg8rozy-nodejs 
  janus-idp.io/tekton: zlqg8rozy-nodejs
  backstage.io/kubernetes-id: zlqg8rozy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zlqg8rozy-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml