apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zlqg8rozy-nodejs
  janus-idp.io/tekton: zlqg8rozy-nodejs
  backstage.io/kubernetes-id: zlqg8rozy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zlqg8rozy-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
